# Generated by Django 5.2.8 on 2025-11-14 13:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("subtitle", models.CharField(blank=True, max_length=250)),
                ("image", models.ImageField(upload_to="banners/")),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="می\u200cتواند لینک یک دسته، محصول یا صفحه خاص باشد.",
                        max_length=300,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("hero", "اسلایدر بزرگ بالای صفحه"),
                            ("special_offer_side", "باکس کنار پیشنهاد ویژه"),
                            ("middle", "بنر وسط صفحه"),
                            ("footer", "بنر پایین صفحه"),
                        ],
                        default="hero",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ["position", "order"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="brands/logos/"),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon_image",
                    models.ImageField(
                        blank=True,
                        help_text="عکس گرد دسته\u200cبندی برای اسلایدر دسته\u200cها.",
                        null=True,
                        upload_to="categories/icons/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در حال بررسی"),
                            ("processing", "در حال آماده\u200cسازی"),
                            ("sent", "ارسال شده"),
                            ("delivered", "تحویل شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_name",
                    models.CharField(default="فروشگاه ایران مارکت", max_length=150),
                ),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="متن معرفی فروشگاه که در صفحه اول نمایش داده می\u200cشود.",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("whatsapp_link", models.URLField(blank=True)),
                ("instagram_link", models.URLField(blank=True)),
                (
                    "delivery_description",
                    models.TextField(
                        blank=True, help_text="مثلاً: ارسال در شهر X در کمتر از ۲ ساعت."
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/main/"
                    ),
                ),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="اگر خالی باشد یعنی تخفیف ندارد.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, help_text="موجودی انبار"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "گرم"),
                            ("kg", "کیلوگرم"),
                            ("ml", "میلی\u200cلیتر"),
                            ("l", "لیتر"),
                            ("pcs", "عدد"),
                            ("pack", "بسته"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="مثلاً 0.9 برای ۹۰۰ گرم یا 1 برای ۱ لیتر.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_best_seller",
                    models.BooleanField(
                        default=False,
                        help_text="نمایش در اسلایدر پرفروش\u200cترین\u200cها",
                    ),
                ),
                (
                    "show_in_special_offer",
                    models.BooleanField(
                        default=False, help_text="نمایش در اسلایدر پیشنهاد ویژه."
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="میانگین امتیاز کاربران، مثلاً 4.35",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="shop.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
    ]
