# Generated by Django 5.2.8 on 2025-11-14 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon_image",
        ),
        migrations.AlterField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.CharField(
                choices=[
                    ("hero", "اسلایدر بزرگ بالای صفحه"),
                    ("special_offer_side", "باکس کنار پیشنهاد ویژه"),
                    ("middle", "بنر وسط صفحه"),
                    ("footer", "بنر پایین صفحه"),
                ],
                db_index=True,
                default="hero",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در حال بررسی"),
                    ("processing", "در حال آماده\u200cسازی"),
                    ("sent", "ارسال شده"),
                    ("delivered", "تحویل شده"),
                    ("cancelled", "لغو شده"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_best_seller",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="نمایش در اسلایدر پرفروش\u200cترین\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="show_in_special_offer",
            field=models.BooleanField(
                db_index=True, default=False, help_text="نمایش در اسلایدر پیشنهاد ویژه."
            ),
        ),
    ]
