# Generated by Django 5.2.8 on 2025-11-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_category_icon_image_alter_banner_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(
                fields=["position", "order"], name="shop_banner_positio_21170f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "order"], name="shop_catego_is_acti_bde3a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="shop_order_status_700268_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["paid", "created_at"], name="shop_order_paid_8a0a7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="shop_produc_is_acti_2d6428_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_best_seller", "is_active"],
                name="shop_produc_is_best_c001e9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["show_in_special_offer", "is_active"],
                name="shop_produc_show_in_71203c_idx",
            ),
        ),
    ]
