# Generated by Django 5.2.8 on 2025-11-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_brand_name_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="shop_catego_is_acti_bde3a1_idx",
        ),
        migrations.AddField(
            model_name="category",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                help_text="عکس گرد دسته\u200cبندی برای نمایش در صفحه اول و لیست دسته\u200cها.",
                null=True,
                upload_to="categories/icons/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
