# Generated by Django 5.2.8 on 2025-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_remove_category_shop_catego_is_acti_bde3a1_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="discount_active",
            field=models.BooleanField(
                default=False,
                help_text="اگر تیک بخورد، این درصد تخفیف روی تمام محصولات فعالِ این دسته اعمال می\u200cشود.",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="discount_percent",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="درصد تخفیف برای کل این دسته (مثلاً 10، 20، 30).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="external_code",
            field=models.CharField(
                blank=True,
                help_text="کد کالا در نرم\u200cافزار باران (برای اتصال خودکار).",
                max_length=50,
                null=True,
            ),
        ),
    ]
