# Generated by Django 5.2.8 on 2025-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_category_discount_active_category_discount_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_index=True,
                        help_text="شماره موبایل یا ایمیل کاربر",
                        max_length=100,
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "کد ورود",
                "verbose_name_plural": "کدهای ورود",
                "ordering": ["-created_at"],
            },
        ),
    ]
