# Generated by Django 5.2.8 on 2025-11-16 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_loginotp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="اگر کاربر موقع ثبت سفارش لاگین بوده باشد، اینجا ذخیره می\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="مثلاً خانه، محل کار",
                        max_length=50,
                        verbose_name="برچسب",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="شهر")),
                (
                    "district",
                    models.CharField(blank=True, max_length=100, verbose_name="محله"),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=150, verbose_name="خیابان"),
                ),
                (
                    "plaque",
                    models.CharField(blank=True, max_length=20, verbose_name="پلاک"),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=20, verbose_name="کد پستی"),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="عرض جغرافیایی"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="طول جغرافیایی"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="آدرس پیش\u200cفرض"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "باز"),
                            ("answered", "پاسخ داده شده"),
                            ("closed", "بسته شده"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(blank=True, verbose_name="پاسخ پشتیبانی"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت پشتیبانی",
                "verbose_name_plural": "تیکت\u200cهای پشتیبانی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام و نام خانوادگی"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "notify_order_sms",
                    models.BooleanField(default=True, verbose_name="پیامک وضعیت سفارش"),
                ),
                (
                    "notify_promotions",
                    models.BooleanField(
                        default=False, verbose_name="اطلاع\u200cرسانی تخفیف\u200cها"
                    ),
                ),
                (
                    "notify_site_notifications",
                    models.BooleanField(
                        default=True, verbose_name="اعلان\u200cهای داخل سایت"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل کاربر",
                "verbose_name_plural": "پروفایل کاربران",
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم علاقه\u200cمندی",
                "verbose_name_plural": "لیست علاقه\u200cمندی\u200cها",
                "unique_together": {("user", "product")},
            },
        ),
    ]
