# Generated by Django 5.2.8 on 2025-11-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_order_user_address_supportticket_userprofile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="نام شهر")),
                ("slug", models.SlugField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="برای نمایش در بخش شهرهای پرتکرار"
                    ),
                ),
                (
                    "delivery_available",
                    models.BooleanField(
                        default=True, help_text="آیا امکان ارسال به این شهر وجود دارد؟"
                    ),
                ),
            ],
            options={
                "verbose_name": "شهر",
                "verbose_name_plural": "شهرها",
                "ordering": ["province__name", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام استان")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "استان",
                "verbose_name_plural": "استان\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="shop.city",
                verbose_name="شهر انتخاب\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="shop.province",
                verbose_name="استان",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("province", "name")},
        ),
    ]
