# Generated by Django 5.2.8 on 2025-11-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_city_province_userprofile_current_city_city_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="free_shipping_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="اگر مجموع سبد از این مبلغ بیشتر شود، ارسال رایگان خواهد شد.",
                null=True,
                verbose_name="آستانه ارسال رایگان (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="shipping_base_fee",
            field=models.PositiveIntegerField(
                default=0,
                help_text="هزینه ارسال معمولی به این شهر، به تومان.",
                verbose_name="هزینه پایه ارسال (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="shop.city",
                verbose_name="شهر ارسال",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="هزینه ارسال"
            ),
        ),
    ]
