# Generated by Django 5.2.8 on 2025-11-18 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_city_free_shipping_threshold_city_shipping_base_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام زون")),
                (
                    "base_shipping_cost",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه پایه ارسال (تومان)"
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر جمع سبد از این مقدار بیشتر شود، ارسال رایگان می\u200cشود. ۰ یعنی هرگز رایگان نیست.",
                        verbose_name="حد آستانه ارسال رایگان (تومان)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "زون ارسال",
                "verbose_name_plural": "زون\u200cهای ارسال",
                "ordering": ["order", "name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="shop_order_status_700268_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="shop_order_paid_8a0a7c_idx",
        ),
        migrations.RemoveField(
            model_name="city",
            name="free_shipping_threshold",
        ),
        migrations.RemoveField(
            model_name="city",
            name="shipping_base_fee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_city",
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="shop.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gateway_tracking_code",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="کد رهگیری درگاه"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_ref",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="شماره پیگیری پرداخت"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="جمع کل با ارسال (تومان)"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="delivery_available",
            field=models.BooleanField(default=True, verbose_name="امکان ارسال"),
        ),
        migrations.AlterField(
            model_name="city",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="city",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="محبوب/پرتکرار"),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام شهر"),
        ),
        migrations.AlterField(
            model_name="city",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="پرداخت شده"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_cost",
            field=models.PositiveIntegerField(
                default=0, verbose_name="هزینه ارسال (تومان)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در حال بررسی"),
                    ("processing", "در حال آماده\u200cسازی"),
                    ("sent", "ارسال شده"),
                    ("delivered", "تحویل شده"),
                    ("cancelled", "لغو شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="shipping_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="shop.shippingzone",
                verbose_name="زون ارسال",
            ),
        ),
    ]
