# Generated by Django 5.2.8 on 2025-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_shippingzone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="توضیح"),
                ),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="مثلاً ۱۰ برای ۱۰٪ تخفیف. اگر خالی باشد، فقط مبلغ ثابت اعمال می\u200cشود.",
                        null=True,
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "discount_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="مثلاً ۵۰۰۰۰ برای ۵۰هزار تومان تخفیف. اگر خالی باشد، فقط درصد تخفیف اعمال می\u200cشود.",
                        null=True,
                        verbose_name="تخفیف ثابت (تومان)",
                    ),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="اگر ۰ باشد، بدون محدودیت است.",
                        verbose_name="حداقل مبلغ سفارش (تومان)",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="فعال")),
                ("valid_from", models.DateTimeField(verbose_name="اعتبار از")),
                ("valid_to", models.DateTimeField(verbose_name="اعتبار تا")),
                (
                    "for_first_order_only",
                    models.BooleanField(
                        default=False, verbose_name="فقط برای اولین سفارش کاربر؟"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کوپن تخفیف",
                "verbose_name_plural": "کوپن\u200cهای تخفیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStats",
            fields=[],
            options={
                "verbose_name": "داشبورد فروش",
                "verbose_name_plural": "داشبورد فروش",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shop.order",),
        ),
    ]
