# Generated by Django 5.2.8 on 2025-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_coupon_orderstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_deducted",
            field=models.BooleanField(
                default=False,
                help_text="برای جلوگیری از کسر دوباره\u200cی موجودی در صورت تأیید پرداخت تکراری.",
                verbose_name="کسر موجودی انجام شده",
            ),
        ),
    ]
