# Generated by Django 5.2.8 on 2025-11-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_order_stock_deducted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="shipping_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="shop.shippingzone",
                verbose_name="زون ارسال",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="base_shipping_cost",
            field=models.PositiveIntegerField(
                help_text="مثلاً ۲۰۰۰۰ برای ۲۰ هزار تومان.",
                verbose_name="هزینه پایه ارسال (تومان)",
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="free_shipping_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="اگر خالی باشد، برای این زون ارسال رایگان نداریم.",
                null=True,
                verbose_name="ارسال رایگان از (تومان)",
            ),
        ),
    ]
